name = "sudoku-worker"
type = "webpack"
account_id = "ee1f7090c167a8f6b95233a76b27075e"
workers_dev = false
route = "a.sudoku-ui.com/*"
zone_id = "ab40201c11f10201f9beb557f3915f86"

[site]
bucket = "./public"